### ISSUE TITLE
style-prefixer is not work in ios 8.4 ( in a cordova app )

### ISSUE THREAD

**Issue by lzhongzh** [FormidableLabs/radium#458]
i currently working on a project which running as a cordova app.
i got the problem after i upgrade radium to 0.15.3 ( previous version is 0.13.8 )

actually the problem appear in module 'inline-style-prefixer'.
  
the userAgent in ios 8.4 is 'Mozilla/5.0 (iPhone; CPU iPhone OS 8_4 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Mobile/12H141 (2073210096)'

and it fail to resovle the version of the device.

ps: i can't upload image in my network circumstance.

### the blamed code is node_modules/inline-style-prefixer/lib/Prefixer.js line 81
> _this._browserInfo.version is NAN, but the _browserInfo.osversion is 8.4

**Comment by ianobermiller** [comment]
cc @rofrischmann, this should probably be an issue in [inline-style-prefixer](https://github.com/rofrischmann/inline-style-prefixer)

**Comment by rofrischmann** [comment]
Seems like an issue with bowser again. Feel free to create an issue at the actual repository @lzhongzh 
Ill be there to help as and find a quick fix for that specific issue until my very own detection module is ready.

**Comment by ianobermiller** [comment]
@rofrischmann Can't recall, is this fixed in i-s-p 0.6.2?

**Comment by rofrischmann** [comment]
It's still not solved, but an issue has been created ( https://github.com/rofrischmann/inline-style-prefixer/issues/40#issuecomment-169019902 ). I thought an issue on bowser, but bowser was last updated in November..
I'll notify when I fixed that

**Comment by alexlande** [comment]
This appears to be resolved as of https://github.com/rofrischmann/inline-style-prefixer/issues/46. If not, leave a comment and we can re-open!
