### ISSUE TITLE
User Select not prefixing 

### ISSUE THREAD

**Issue by mashaal** [FormidableLabs/radium#844]
User Select is not currently prefixing -- tested in Chrome and Firefox on Radium `0.18.1`. It does work if you manually define the vendor prefixes ( `WebkitUserSelect` and `MozUserSelect`)

**Comment by evtuhovdo** [comment]
Its becouse new browser vertion is not listed in inline-prefixer lists. If their list have last vertion chrome 53, but in your pc you have 54 you will no get any ptefix. I use custom radium plugin, wich use inline prefixer, write me i will help with code if you need.

**Comment by yrokhlin** [comment]
+1 to this, a bit annoying!

**Comment by josiahsprague** [comment]
@evtuhovdo Can you share the custom code you're using? I'm looking at https://github.com/rofrischmann/inline-style-prefixer but it seems like it should support the latest browser versions.

**Comment by begincalendar** [comment]
I'm not getting prefixing for Firefox 50.1.0 on Ubuntu.
Works for Chromium though.

I'm using Radium version 0.18.1

**Comment by montanonic** [comment]
Likewise: no prefixing with `userSelect` for Firefox 50.1.0 on Ubuntu.

**Comment by alexlande** [comment]
This should hopefully have been fixed by an inline-style-prefixer version bump a long time ago. If not, I'm planning to upgrade that library again which will likely fix more issues like this. Sorry for the trouble!

**Comment by keeganstothert** [comment]
this is still an issue for firefox 57, user-select is not being vendor prefixed

**Comment by ryan-roemer** [comment]
@keeganstothert -- Can you report on if this is fixed in latest radium version now that we've bumped ISP?

**Comment by stevenmusumeche** [comment]
ping @keeganstothert
